apiVersion: 1

datasources:
  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428/
    uid: victorialogs
    jsonData:
      derivedFields:
        - name: traceID
          matcherName: trace_id
          datasourceUid: victoriatraces

  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428/

  - name: VictoriaTraces
    type: jaeger
    access: proxy
    url: http://victoriatraces:10428/select/jaeger
    uid: victoriatraces
    jsonData:
      tracesToLogsV2:
        datasourceUid: victorialogs
        filterByTraceID: true